name: Build On Pull Request

on:
  pull_request:
    branches: [ "master", "main" ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code with submodule
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          submodules: true
          fetch-depth: 0 

      - name: Update submodules
        run: |
          git submodule init
          git submodule update --recursive

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          
      - name: Build with NPM
        run: |
          npm config set legacy-peer-deps true
          npm ci 
          npm run build